#!/usr/bin/python
import os
import gi

gi.require_version("Gtk", "3.0")
gi.require_version("AppIndicator3", "0.1")
from gi.repository import Gtk as gtk, AppIndicator3 as appindicator


def main():
    indicator = appindicator.Indicator.new(
        "powertray",
        "system-shutdown-symbolic",
        appindicator.IndicatorCategory.APPLICATION_STATUS,
    )
    indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
    indicator.set_menu(menu())
    gtk.main()


def menu():
    menu = gtk.Menu()

    GTK_ICON_SIZE_MENU = 16

    lock = gtk.ImageMenuItem()
    lockimage = gtk.Image()
    lockimage.set_from_icon_name("system-lock-screen-symbolic", GTK_ICON_SIZE_MENU)
    lock.set_image(lockimage)
    lock.set_always_show_image(True)
    lock.set_label("Lock")
    lock.connect("activate", lock_screen)
    menu.append(lock)

    logout = gtk.ImageMenuItem()
    logoutimage = gtk.Image()
    logoutimage.set_from_icon_name("system-log-out-symbolic", GTK_ICON_SIZE_MENU)
    logout.set_image(logoutimage)
    logout.set_always_show_image(True)
    logout.set_label("Exit")
    logout.connect("activate", exit_sway)
    menu.append(logout)

    reboot = gtk.ImageMenuItem()
    rebootimage = gtk.Image()
    rebootimage.set_from_icon_name("system-reboot-symbolic", GTK_ICON_SIZE_MENU)
    reboot.set_image(rebootimage)
    reboot.set_always_show_image(True)
    reboot.set_label("Reboot")
    reboot.connect("activate", reboot_system)
    menu.append(reboot)

    shutdown = gtk.ImageMenuItem()
    shutdownimage = gtk.Image()
    shutdownimage.set_from_icon_name("system-shutdown-symbolic", GTK_ICON_SIZE_MENU)
    shutdown.set_image(shutdownimage)
    shutdown.set_always_show_image(True)
    shutdown.set_label("Shutdown")
    shutdown.connect("activate", shutdown_system)
    menu.append(shutdown)

    menu.show_all()
    return menu


def lock_screen(_):
    os.system("swaylock")


def exit_sway(_):
    os.system("swaymsg exit")


def reboot_system(_):
    os.system("systemctl reboot")


def shutdown_system(_):
    os.system("systemctl poweroff")


if __name__ == "__main__":
    main()
