#!/bin/sh


essid=$(nmcli | grep -v "disconnected" | grep "connected" | awk '{print $4}')
wstatus=$(nmcli | grep -v "disconnected" | grep connected | awk '{print $2}')

if [ "$wstatus" = "connected" ]
then
  icon=" "
else
  icon="睊"
  essid="disconnected"
fi

printf "%s\n" "$icon $essid"
