#!/bin/bash

battery="/sys/class/power_supply/BAT0/"

capacity=$(cat "$battery"/capacity)
bstatus=$(cat "$battery"/status)

if [ "$bstatus" = "Charging" ] || [ "$bstatus" = "Unknown" ]; then
    icon=""
elif [ "$bstatus" = "Full" ]; then
    icon=""
elif [ "$bstatus" = "Discharging" ]; then
    if [ $capacity -gt 75 ]; then
        icon=""
    elif [ $capacity -lt 25 ]; then
        icon=""
    else
        icon=""
    fi
else
    icon=""
fi


printf "%s%% \n" "^c#2e3440^^b#5e81ac^ $icon ^c#5e81ac^^b#2e3440^ $capacity"
