#!/bin/bash

wm=$(cat ~/.xinitrc | grep "exec" | awk '{print $2}')
battery="/sys/class/power_supply/BAT0/"

capacity=$(cat "$battery"/capacity)
bstatus=$(cat "$battery"/status)

if [ "$bstatus" = "Charging" ]; then
    if [ $capacity -eq 100 ]; then
        icon=""
    elif [ $capacity -gt 85 ]; then
        icon=""
    elif [ $capacity -gt 70 ]; then
        icon=""
    elif [ $capacity -lt 30 ]; then
        icon=""
    elif [ $capacity -lt 10 ]; then
        icon=""
    else
        icon=""
    fi
elif [ "$bstatus" = "Unknown" ]; then
    icon=""
elif [ "$bstatus" = "Full" ]; then
    icon=""
elif [ "$bstatus" = "Discharging" ]; then
    if [ $capacity -eq 100 ]; then
        icon=""
    elif [ $capacity -gt 85 ]; then
        icon=""
    elif [ $capacity -gt 70 ]; then
        icon=""
    elif [ $capacity -lt 40 ]; then
        icon=""
    elif [ $capacity -lt 10 ]; then
        icon=""
    else
        icon=""
    fi
else
    icon=""
fi

if [ "$wm" = "dwm" ]; then
    printf "%s%% \n" "^c#282c34^^b#61afef^ $icon ^c#abb2bf^^b#282c34^ $capacity"
elif [ "$wm" = "spectrwm" ]; then
    printf "%s%%  \n" "+@fg=4;$icon+@fg=7; $capacity"
else
    printf "%s%% \n" "$icon $capacity"
fi
