#!/bin/sh

trap 'update' 5

net() {
    internet
}

ctime() {
    clock
}

bat() {
    battery
}

vol() {
    volume
}

bri() {
    brightness
}

kbd() {
    kbdlayout
}

screens() {
    screenstatus
}
wthr() {
    weather
}

update() {
    xsetroot -name "$(screens)$(kbd)$(wthr)$(bri)$(volume)$(ctime)$(net)" &
    wait
}

while :; do
    update
    sleep 10 &
    wait
done
