#!/bin/sh

trap 'update' 5

net() {
    internet
}

time() {
    clock
}

vol() {
    volume
}

bri() {
    brightness
}

kbd() {
    kbdlayout
}

screens() {
    screenstatus
}

update() {
    xsetroot -name "$(screens)$(kbd)$(bri)$(volume)$(time)$(net | tr '\n' ' ')" &
    wait
}

while :; do
    update
    sleep 10 &
    wait
done
