#!/bin/sh


essid=$(nmcli | grep -v "disconnected" | grep "connected" | awk '{print $4}')
wstatus=$(nmcli | grep -v "disconnected" | grep connected | awk '{print $2}')

if [ "$wstatus" = "connected" ]
then
  icon=""
else
  icon=""
  essid="disconnected"
fi

printf "%s\n" "^c#282c34^^b#be5046^ $icon ^c#abb2bf^^b#282c34^ $essid ^d^"
