#!/bin/sh

wm=$(cat ~/.xinitrc | grep "exec" | awk '{print $2}')
sstatus=$(xrandr --listactivemonitors | grep "Monitors" | awk '{print $2}')

if [ "$sstatus" -eq 1 ]; then
    text="Single"
    icon=""
else
    text="Dual"
    icon=""
fi

if [ "$wm" = "dwm" ]; then
    printf "%s\n" "^c#282c34^^b#e06c75^ $icon ^c#abb2bf^^b#282c34^ $text ^d^"
elif [ "$wm" = "spectrwm" ]; then
    printf "%s \n" "+@fg=7;$icon+@fg=7; "
else
    printf "%s\n" "$icon $sstatus "
fi
