#!/bin/sh

volstat=$(pamixer --get-volume)

vol=$(echo "$volstat")


if [ "$vol" -gt "70" ]; then
	icon=" "
elif [ "$vol" -eq "0" ]; then
    icon="婢"
elif [ "$vol" -lt "30" ]; then
	icon=""

else
	icon="墳"
fi

printf "%s%% \n" "$icon $volstat"
