#!/bin/sh

volstat="$(pamixer --get-volume)" # ALSA only equivalent.

vol=$(echo "$volstat")

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon=""
fi

printf "%s%%\\n" "^c#2e3440^^b#ebcb8b^ $icon ^ d^^c#ebcb8b ^ $vol"
