#!/bin/sh

report="$HOME/.local/share/weatherreport"

getforecast() { curl -sf "wttr.in?format="%C:+%t"" > "${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" || exit 1 ;}

[ "$(stat -c %y "${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] || getforecast

condition=$(cat $report | awk -F ":" '{print $1}' | sed 's/ //g')
temp=$(cat $report | awk  -F ":" '{print $2}' | sed 's/ //g;s/+//g')

case "$condition" in
    Sunny) icon="" ;;
    Partlycloudy) icon="" ;;
    Cloudy|Verycloudy) icon="" ;;
    Fog) icon="" ;;
    Lightshowers|Lightsleetshowers|Lightsleet|Lightrain) icon="" ;;
    Heavyshowers|Heavyrain) icon="" ;;
    Lightsnow|Lightsnowshowers) icon="" ;;
    Heavysnow|Heavysnowshowers) icon="" ;;
    Thunderyshowers|Thunderyheavyrain)  icon="" ;;
    Thunderysnowshowers) icon=""
esac


printf "%s\n" "^c#282c34^^b#abb2bf^ $icon ^c#abb2bf^^b#282c34^ $temp ^d^"




